name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Switch to Xcode 12
      run: sudo xcode-select -s /Applications/Xcode_12.app
    - name: Show Available Destinations
      run: |
        cd Application
        xcodebuild -scheme To-Do -showdestinations
    - name: Build
      env: 
        PROJECT: To-Do.xcodeproj
        SCHEME: To-Do
        DESTINATION: platform=iOS Simulator,OS=14.0,name=iPhone 11
      run: |
        cd Application
        xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release build CODE_SIGNING_ALLOWED=NO
